### ISSUE TITLE
Do not process issue descriptions

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/GitHub-Issue-Classifier#47]
Only process (classify) issue comments. Please ignore description.

**Comment by y3pio** [comment]
Just to clarify, currently a sample `commentURL` is as follows: https://github.com/q-optimize/c3/issues/74

But it should instead be: https://github.com/q-optimize/c3/issues/74#issue-835058056
which anchors us to the specific comment for the result that we are looking at? (in the case of this issue, there's only 1 comment)

**Comment by khatchad** [comment]
> Just to clarify, currently a sample `commentURL` is as follows: ["https://github.com/q-optimize/c3/issues/74"](https://github.com/q-optimize/c3/issues/74)

Yes.

> But it should instead be: ["https://github.com/q-optimize/c3/issues/74#issue-835058056"](https://github.com/q-optimize/c3/issues/74#issue-835058056)
> which anchors us to the specific comment for the result that we are looking at?

Yes.

> (in the case of this issue, there's only 1 comment)

If that is the case, there should still be an anchor. I am just going off what I expect to see per CSV column name. My assumption is that you wouldn't deliberately have two columns with the same data.

**Comment by y3pio** [comment]
Yup, agreed. I will look into this to see if the API provides any way to append comment ID's to the end of the URL to anchor us to the specific comment.

**Comment by khatchad** [comment]
I would think that this information is given in the response JSON.

**Comment by khatchad** [comment]
https://docs.github.com/en/rest/reference/issues#comments

**Comment by y3pio** [comment]
Hi Professor, it seems like I'm already anchoring the comments. I think for issues with just one comment, it somehow shows up as the same URL as the issue URL. Per their API docs, the `html_url` field that I am using for the column should have an `#issue-12345` pattern, but however the API seems to just return the main issue URL without the anchor. Below is the API call for the issue above that I mentioned:

https://api.github.com/repos/q-optimize/c3/issues/74

As you can see the `html_url` field does not contain the `#issue-...` anchor as the docs indicate. But for the comments found in the `comments_url` API call, I believe the tool is anchoring them accordingly.

Please let me know if my explanation is clear, happy to walk through this over a call if needed.

**Comment by khatchad** [comment]
> Hi Professor, it seems like I'm already anchoring the comments.

At a quick glance, I didn't see any such anchoring. The ones I saw did not include anchors. Do you have any counter evidence?

> I think for issues with just one comment, it somehow shows up as the same URL as the issue URL. 

But not all issues will have only one comment. If this is the case, we should have *at least* one example of an anchored URL, right? Another examples of evidence would be the location in the code where this field is being populated.

> Per their API docs, the `html_url` field that I am using for the column should have an `#issue-12345` pattern, but however the API seems to just return the main issue URL without the anchor.

In all cases or just cases where there is only one comment?

> Below is the API call for the issue above that I mentioned:
> 
> https://api.github.com/repos/q-optimize/c3/issues/74

There are no comments in this issue. Do we process issues with no comments?

> As you can see the `html_url` field does not contain the `#issue-...` anchor as the docs indicate.

That's because it doesn't have any comments. In other words, https://api.github.com/repos/q-optimize/c3/issues/74/comments gives a empty array.

> But for the comments found in the `comments_url` API call, I believe the tool is anchoring them accordingly.

My impression is that the dataset is a list of issue comments. Why are we examining an issue that has no comments? Or, do you treat issue descriptions as comments?

> Please let me know if my explanation is clear, happy to walk through this over a call if needed.

I think it makes me more confused :). Sure, let's do a call. Please send me a calendar invite when you have a chance. Thanks @y3pio.
